### ISSUE TITLE
SSL Cert change

### ISSUE THREAD

**Issue by athal7** [avadev/AvaTax-SOAP-Ruby-SDK#1]
Is anything necessary for customers using this integration for the upcoming [SSL cert change](https://help.avalara.com/kb/Avatax_Certificate_Change_July_2015)? It does not appear so to me, but I was hoping someone from the Avalara development team can either confirm or release a new version for us to use.

Thanks!

**Comment by anyarms** [comment]
This library does not require the certificate to be manually installed, so there is no change needed to accommodate this update. If you needed to manually install the certificate for another reason (setup restriction, etc), then you will need to manually re-install the new certificate.

**Comment by anyarms** [comment]
Actually... reopening this to change the service URL from a boolean to a string. That will allow you to test against the alternate URL if needed.

**Comment by athal7** [comment]
@anyarms thanks. It sounds like I don't need to test against the alternate URL though unless I've done something explicit to manually install the cert, right?

**Comment by anyarms** [comment]
@athal7 That's right. The alternate URLs allow you to manually specify the endpoint (each of which has a different certificate version) if you're feeling extra cautious, but if you take no action you'll just roll over to the new cert.

**Comment by anyarms** [comment]
Released v 2.0.1, which allows the service URL to be specified rather than choosing just dev vs. prod
