### ISSUE TITLE
uninitialized constant AvaTax

### ISSUE THREAD

**Issue by edudepetris** [avadev/AvaTax-SOAP-Ruby-SDK#2]
Hi! 
I'm trying to use this gem to calculate Tax and I don't get it works. This is my example code

```rb
module Taxs
  class << self
    def calculate
      AvaTax::TaxService.new
    end
  end
end
```

In my rails console
```sh
Taxs.calculate # => NameError: uninitialized constant AvaTax
```

```rb
# Gemfile
ruby '2.1.2'
gem 'rails', '4.2.0'
gem 'Avatax_TaxService', '~> 2.0.2'

```

Can you give me some help?

**Comment by anyarms** [comment]
@edudepetris Sounds like there's an issue with the way you're loading/referring to the gem - everything looks OK here (no chance you neglected to `bundle install` ?) I'm able to get a different (expected) error when I try your code:

    Taxs.calculate
    ArgumentError: wrong number of arguments (0 for 1)

If I omit  `require "Avatax_TaxService"` I get the same error you see.

**Comment by kamui** [comment]
To fix this I had to put this in my Gemfile:

```ruby
gem 'Avatax_TaxService', '~>2.0.0', require: "avatax_taxservice"
```

My guess is perhaps a problem with case sensitive file systems. On OS X, this works without requiring the `lib/avatax_taxservice`, but when trying to deploy this on a linux with ex4, it fails to load anything for this gem.

**Comment by anyarms** [comment]
Thanks @kamui - I'll add that to the readme.
